# This default stack file is a copy of stack-ghc8.10.7.yaml
# But committing a symlink can be problematic on Windows, so it's a real copy.
# See: https://github.com/GrammaticalFramework/gf-core/pull/106
resolver: lts-18.27 # ghc 8.10.7

extra-deps:
- network-2.6.3.6
- httpd-shed-0.4.0.3

# flags:
#   gf:
#     server: true
#     c-runtime: true
# extra-lib-dirs:
#   - /usr/local/lib
